### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mr-attacker** [vpnguy/ntpdos#4]
how can use it?? 

![image](https://cloud.githubusercontent.com/assets/19631231/15937284/7b68008c-2e83-11e6-88c0-44188ae4dd22.png)

dont workeeed

**Comment by vpnguy** [comment]
You cannot execute it inside codeanywhere.com, additionally you need to either chmod +x the script then call it with bash or execute it directly with the python binary.

Error is between keyboard and chair with this one.
